name: Docker Build Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Get shortened SHA
      id: shorten_sha
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
        echo "::set-output name=short_sha::${SHORT_SHA}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USR }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        GIT_HASH: ${{ steps.shorten_sha.outputs.short_sha }}
      run: |
        if [[ $COMMIT_MESSAGE == *"DEPLOY_DEV"* ]]; then
          docker buildx build --build-arg commit_sha=$GIT_HASH -t ghcr.io/scalr-dex/scalr-frontend:develop . --push
        else
          echo "No action defined for this branch/tag."
        fi
