name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    environment:
      name: dev-pages

    steps:
      - name: Trigger Dev Deploy
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.FRONTEND_DEV_HOST }}
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
