name: Build and deploy app

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy-app:
    if: contains(github.event.head_commit.message, '[DEV_DEPLOY]')
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: dev-pages
      url: ${{ secrets.DEV_FRONT_URL }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install modules
        run: yarn
        shell: bash
      - name: Build code
        run: yarn build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_DEV_BACKEND_URL }}
          VITE_AMPLITUDE_API_KEY: ${{ secrets.VITE_AMPLITUDE_API_KEY }}
          VITE_APP_BASE_LINK: ${{ secrets.VITE_DEV_APP_BASE_LINK }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
        shell: bash
      - name: Setup Dev Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to Dev Pages
        id: deployment
        uses: actions/deploy-pages@v1
