name: Build and lint code
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: ./.github/workflows/buildLint.yml
